### ISSUE TITLE
about dataset preparation 

### ISSUE THREAD

**Issue by Tihetna1891** [nihofm/ndptmvd#1]
Hello,
I was working on my Master's thesis using this paper as a baseline but I really need your help in preparing the datasets. so, what was the renderer that you have used for preparing both the noisy and clean data?
if that is not too much trouble can you help me with providing your volume renderer?
when I prepared some datasets with blender cycle path tracer to try the denoiser the following error keeps happening

  args: Namespace(amp=False, batch_size=4, beta1=0.9, beta2=0.999, big=False, checkpoint=None, clip=1, epochs=250, features=[], learning_rate=0.0002, loss='hfs', name='image_hfs_default', type='image', workers=4, x_train='/path/to/data/noisy', x_val='/path/to/data/validation/noisy', y_train='/path/to/data/clean', y_val='/path/to/data/validation/clean')
Using device: cuda
Num GPUs: 1
Loading train dataset from /path/to/data/noisy and /path/to/data/clean...
Traceback (most recent call last):
  File "src/train.py", line 118, in <module>
    data_train = data.DataSetTrain(args.x_train, args.y_train, args.features)
  File "/content/drive/MyDrive/ndptmvd-master/ndptmvd-master/src/data.py", line 285, in __init__
    self.data_x = make_dataset(dir_x, True)
  File "/content/drive/MyDrive/ndptmvd-master/ndptmvd-master/src/data.py", line 204, in make_dataset
    return h5py.File(filename, 'r')['data']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"

**Comment by BRAIN-RICH** [comment]
Did you find the dataset or otherreplacement？

**Comment by ChenZhiMing66** [comment]
Hello, 
I am reproducing the experimental results mentioned in your paper.  I also need your help in preparing the datasets. So is it convenient for you to provide some alternative data sets for reference. Or can you tell me what your renderer is for preparing noisy and clean data.
If that is not too much trouble can you help me with providing your volume renderer?
I really need your help. Thank you very much!!!

**Comment by nihofm** [comment]
Hi,
I'm sorry, but it turned out to be impossible for us to publish any of the datasets due to data protection laws.
The cinematic renderer used in the paper is also not available to the public, so we're unfortunately unable to help you there, either.
However, I've just publicly released a volume renderer that is capable of generating volume denoising datasets. It produces datasets in hdf5 format, so with adapting the dataloader, you should be able to make something work. You can find it here: https://github.com/nihofm/volren
Best of luck with your project!
