### ISSUE TITLE
When is the code for this article intended to be made public？

### ISSUE THREAD

**Issue by Songxinlei** [nihofm/ndptmvd#4]
Hello, I would like to ask when the code for this article about"**Joint Neural Denoising of Surfaces and Volumes**" is going to be made public? I would appreciate it if you could get back to me.

**Comment by nihofm** [comment]
Hi, unfortunately the code for the paper you mentioned is under NDA and thus can not be released to the public. I am happy to answer questions, but there will not be any code released.

**Comment by Songxinlei** [comment]
Thank your reply！



发自我的iPhone


------------------ Original ------------------
From: Nikolai Hofmann ***@***.***&gt;
Date: Thu,Apr 25,2024 6:03 PM
To: nihofm/ndptmvd ***@***.***&gt;
Cc: Mo_Eagle ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [nihofm/ndptmvd] When is the code for this article intended to be made public？ (Issue #4)
